import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Platform,
  Dimensions,
  Alert,
  Share,
  Linking,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const { width } = Dimensions.get('window');
const isTablet = width >= 768;

interface AttendanceData {
  date: string;
  present: number;
  absent: number;
  total: number;
}

export default function ReportsScreen() {
  const [selectedPeriod, setSelectedPeriod] = useState('This Week');
  const [selectedClass, setSelectedClass] = useState('All Classes');
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportHistory, setReportHistory] = useState<any[]>([]);

  const periods = ['Today', 'This Week', 'This Month', 'This Semester', 'Custom Range'];
  const classes = ['All Classes', 'CS Year 1', 'CS Year 2', 'CS Year 3', 'IT Year 1', 'IT Year 2'];

  const attendanceData: AttendanceData[] = [
    { date: '2024-01-15', present: 42, absent: 8, total: 50 },
    { date: '2024-01-16', present: 45, absent: 5, total: 50 },
    { date: '2024-01-17', present: 38, absent: 12, total: 50 },
    { date: '2024-01-18', present: 47, absent: 3, total: 50 },
    { date: '2024-01-19', present: 44, absent: 6, total: 50 },
  ];

  const totalPresent = attendanceData.reduce((sum, day) => sum + day.present, 0);
  const totalAbsent = attendanceData.reduce((sum, day) => sum + day.absent, 0);
  const totalStudents = attendanceData.reduce((sum, day) => sum + day.total, 0);
  const averageAttendance = totalStudents > 0 ? ((totalPresent / totalStudents) * 100).toFixed(1) : '0';

  // Additional analytics
  const highestAttendance = Math.max(...attendanceData.map(d => (d.present / d.total) * 100));
  const lowestAttendance = Math.min(...attendanceData.map(d => (d.present / d.total) * 100));
  const trendDirection = attendanceData.length > 1 ? 
    (attendanceData[attendanceData.length - 1].present / attendanceData[attendanceData.length - 1].total) > 
    (attendanceData[0].present / attendanceData[0].total) ? 'up' : 'down' : 'stable';

  useEffect(() => {
    loadReportHistory();
  }, []);

  const loadReportHistory = async () => {
    try {
      const history = await AsyncStorage.getItem('reportHistory');
      if (history) {
        setReportHistory(JSON.parse(history));
      }
    } catch (error) {
      console.error('Error loading report history:', error);
    }
  };

  const saveReportToHistory = async (reportData: any) => {
    try {
      const newReport = {
        id: Date.now(),
        ...reportData,
        createdAt: new Date().toISOString(),
      };
      const updatedHistory = [newReport, ...reportHistory.slice(0, 9)]; // Keep last 10 reports
      setReportHistory(updatedHistory);
      await AsyncStorage.setItem('reportHistory', JSON.stringify(updatedHistory));
    } catch (error) {
      console.error('Error saving report history:', error);
    }
  };

  const generateReport = async (format: string) => {
    setIsGenerating(true);
    try {
      // Simulate report generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const reportData = {
        period: selectedPeriod,
        class: selectedClass,
        format,
        totalPresent,
        totalAbsent,
        averageAttendance,
        highestAttendance: highestAttendance.toFixed(1),
        lowestAttendance: lowestAttendance.toFixed(1),
        trend: trendDirection,
      };

      await saveReportToHistory(reportData);

      Alert.alert(
        'Report Generated',
        `${format.toUpperCase()} report for ${selectedClass} (${selectedPeriod}) has been generated successfully.`,
        [
          { text: 'OK' },
          { 
            text: 'Share', 
            onPress: () => shareReport(reportData)
          }
        ]
      );
    } catch (error) {
      Alert.alert('Error', 'Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const shareReport = async (reportData: any) => {
    try {
      const reportText = `
Faculty ERP - Attendance Report

Period: ${reportData.period}
Class: ${reportData.class}
Generated: ${new Date(reportData.createdAt).toLocaleDateString()}

Summary:
• Average Attendance: ${reportData.averageAttendance}%
• Total Present: ${reportData.totalPresent}
• Total Absent: ${reportData.totalAbsent}
• Highest Day: ${reportData.highestAttendance}%
• Lowest Day: ${reportData.lowestAttendance}%
• Trend: ${reportData.trend === 'up' ? 'Improving' : reportData.trend === 'down' ? 'Declining' : 'Stable'}

Generated by Faculty ERP
      `;

      await Share.share({
        message: reportText,
        title: 'Attendance Report',
      });
    } catch (error) {
      console.error('Error sharing report:', error);
    }
  };

  const emailReport = () => {
    const subject = `Attendance Report - ${selectedClass} (${selectedPeriod})`;
    const body = `Please find the attendance report attached.\n\nPeriod: ${selectedPeriod}\nClass: ${selectedClass}\nAverage Attendance: ${averageAttendance}%`;
    
    Linking.openURL(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);
  };

  const scheduleReport = () => {
    Alert.alert(
      'Schedule Report',
      'Set up automatic report generation',
      [
        { text: 'Daily', onPress: () => Alert.alert('Scheduled', 'Daily reports will be generated at 6 PM') },
        { text: 'Weekly', onPress: () => Alert.alert('Scheduled', 'Weekly reports will be generated every Sunday') },
        { text: 'Monthly', onPress: () => Alert.alert('Scheduled', 'Monthly reports will be generated on the 1st of each month') },
        { text: 'Cancel', style: 'cancel' },
      ]
    );
  };

  const renderIcon = (name: string, size: number, color: string) => (
    <Text style={{ fontSize: size, color }}>{name}</Text>
  );

  return (
    <View style={{ flex: 1, backgroundColor: '#f0f9ff' }}>
      {/* Header */}
      <View style={{
        backgroundColor: '#ffffff',
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: 24,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
      }}>
        <Text style={{
          fontSize: 28,
          fontWeight: '700',
          color: '#1f2937',
          marginBottom: 8,
        }}>
          Attendance Reports
        </Text>
        <Text style={{
          fontSize: 16,
          color: '#6b7280',
          fontWeight: '500',
        }}>
          View detailed attendance analytics and reports
        </Text>
      </View>

      <ScrollView style={{ flex: 1 }} showsVerticalScrollIndicator={false}>
        <View style={{ padding: 24 }}>
          {/* Filter Section */}
          <View style={{
            backgroundColor: '#ffffff',
            borderRadius: 16,
            padding: 20,
            marginBottom: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 3,
          }}>
            <Text style={{
              fontSize: 18,
              fontWeight: '600',
              color: '#1f2937',
              marginBottom: 16,
            }}>
              Report Filters
            </Text>

            <View style={{ marginBottom: 16 }}>
              <Text style={{
                fontSize: 14,
                fontWeight: '500',
                color: '#374151',
                marginBottom: 8,
              }}>
                Time Period
              </Text>
              <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                <View style={{ flexDirection: 'row', gap: 8 }}>
                  {periods.map((period) => (
                    <TouchableOpacity
                      key={period}
                      onPress={() => setSelectedPeriod(period)}
                      style={{
                        paddingHorizontal: 16,
                        paddingVertical: 10,
                        borderRadius: 8,
                        backgroundColor: selectedPeriod === period ? '#06b6d4' : '#f3f4f6',
                        borderWidth: 1,
                        borderColor: selectedPeriod === period ? '#06b6d4' : '#e5e7eb',
                      }}
                    >
                      <Text style={{
                        fontSize: 14,
                        fontWeight: '500',
                        color: selectedPeriod === period ? '#ffffff' : '#374151',
                      }}>
                        {period}
                      </Text>
                    </TouchableOpacity>
                  ))}
                </View>
              </ScrollView>
            </View>

            <View>
              <Text style={{
                fontSize: 14,
                fontWeight: '500',
                color: '#374151',
                marginBottom: 8,
              }}>
                Class
              </Text>
              <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                <View style={{ flexDirection: 'row', gap: 8 }}>
                  {classes.map((className) => (
                    <TouchableOpacity
                      key={className}
                      onPress={() => setSelectedClass(className)}
                      style={{
                        paddingHorizontal: 16,
                        paddingVertical: 10,
                        borderRadius: 8,
                        backgroundColor: selectedClass === className ? '#06b6d4' : '#f3f4f6',
                        borderWidth: 1,
                        borderColor: selectedClass === className ? '#06b6d4' : '#e5e7eb',
                      }}
                    >
                      <Text style={{
                        fontSize: 14,
                        fontWeight: '500',
                        color: selectedClass === className ? '#ffffff' : '#374151',
                      }}>
                        {className}
                      </Text>
                    </TouchableOpacity>
                  ))}
                </View>
              </ScrollView>
            </View>
          </View>

          {/* Summary Stats */}
          <View style={{
            flexDirection: isTablet ? 'row' : 'column',
            gap: 16,
            marginBottom: 24,
          }}>
            <View style={{
              flex: 1,
              backgroundColor: '#ffffff',
              borderRadius: 16,
              padding: 20,
              shadowColor: '#000',
              shadowOffset: { width: 0, height: 2 },
              shadowOpacity: 0.05,
              shadowRadius: 8,
              elevation: 3,
              borderLeftWidth: 4,
              borderLeftColor: '#10b981',
            }}>
              <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 4 }}>
                <Text style={{
                  fontSize: 32,
                  fontWeight: '700',
                  color: '#10b981',
                  marginRight: 8,
                }}>
                  {averageAttendance}%
                </Text>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                  {trendDirection === 'up' ? renderIcon('trending-up' as any, 18, '#10b981') : trendDirection === 'down' ? renderIcon('trending-down' as any, 18, '#ef4444') : renderIcon('more' as any, 18, '#6b7280')}
                </View>
              </View>
              <Text style={{
                fontSize: 16,
                color: '#6b7280',
                fontWeight: '500',
              }}>
                Average Attendance Rate
              </Text>
            </View>

            <View style={{
              flex: 1,
              backgroundColor: '#ffffff',
              borderRadius: 16,
              padding: 20,
              shadowColor: '#000',
              shadowOffset: { width: 0, height: 2 },
              shadowOpacity: 0.05,
              shadowRadius: 8,
              elevation: 3,
              borderLeftWidth: 4,
              borderLeftColor: '#3b82f6',
            }}>
              <Text style={{
                fontSize: 32,
                fontWeight: '700',
                color: '#3b82f6',
                marginBottom: 4,
              }}>
                {totalPresent}
              </Text>
              <Text style={{
                fontSize: 16,
                color: '#6b7280',
                fontWeight: '500',
              }}>
                Students Present
              </Text>
            </View>

            <View style={{
              flex: 1,
              backgroundColor: '#ffffff',
              borderRadius: 16,
              padding: 20,
              shadowColor: '#000',
              shadowOffset: { width: 0, height: 2 },
              shadowOpacity: 0.05,
              shadowRadius: 8,
              elevation: 3,
              borderLeftWidth: 4,
              borderLeftColor: '#ef4444',
            }}>
              <Text style={{
                fontSize: 32,
                fontWeight: '700',
                color: '#ef4444',
                marginBottom: 4,
              }}>
                {totalAbsent}
              </Text>
              <Text style={{
                fontSize: 16,
                color: '#6b7280',
                fontWeight: '500',
              }}>
                Students Absent
              </Text>
            </View>
          </View>

          {/* Advanced Analytics */}
          <View style={{
            backgroundColor: '#ffffff',
            borderRadius: 16,
            padding: 20,
            marginBottom: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 3,
          }}>
            <Text style={{
              fontSize: 18,
              fontWeight: '600',
              color: '#1f2937',
              marginBottom: 16,
            }}>
              Advanced Analytics
            </Text>

            <View style={{
              flexDirection: isTablet ? 'row' : 'column',
              gap: 16,
            }}>
              <View style={{
                flex: 1,
                backgroundColor: '#f0fdf4',
                borderRadius: 12,
                padding: 16,
                borderWidth: 1,
                borderColor: '#bbf7d0',
              }}>
                <Text style={{
                  fontSize: 20,
                  fontWeight: '700',
                  color: '#15803d',
                  marginBottom: 4,
                }}>
                  {highestAttendance.toFixed(1)}%
                </Text>
                <Text style={{
                  fontSize: 14,
                  color: '#166534',
                  fontWeight: '500',
                }}>
                  Best Attendance Day
                </Text>
              </View>

              <View style={{
                flex: 1,
                backgroundColor: '#fef2f2',
                borderRadius: 12,
                padding: 16,
                borderWidth: 1,
                borderColor: '#fecaca',
              }}>
                <Text style={{
                  fontSize: 20,
                  fontWeight: '700',
                  color: '#dc2626',
                  marginBottom: 4,
                }}>
                  {lowestAttendance.toFixed(1)}%
                </Text>
                <Text style={{
                  fontSize: 14,
                  color: '#991b1b',
                  fontWeight: '500',
                }}>
                  Lowest Attendance Day
                </Text>
              </View>

              <View style={{
                flex: 1,
                backgroundColor: '#f0f9ff',
                borderRadius: 12,
                padding: 16,
                borderWidth: 1,
                borderColor: '#bae6fd',
              }}>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                  {trendDirection === 'up' ? renderIcon('trending-up' as any, 18, '#10b981') : trendDirection === 'down' ? renderIcon('trending-down' as any, 18, '#ef4444') : renderIcon('more' as any, 18, '#6b7280')}
                </View>
                <Text style={{
                  fontSize: 14,
                  color: '#0c4a6e',
                  fontWeight: '500',
                }}>
                  Attendance Trend: {trendDirection === 'up' ? 'Improving' : trendDirection === 'down' ? 'Declining' : 'Stable'}
                </Text>
              </View>
            </View>
          </View>

          {/* Daily Breakdown */}
          <View style={{
            backgroundColor: '#ffffff',
            borderRadius: 16,
            padding: 20,
            marginBottom: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 8,
            elevation: 3,
          }}>
            <Text style={{
              fontSize: 18,
              fontWeight: '600',
              color: '#1f2937',
              marginBottom: 16,
            }}>
              Daily Attendance Breakdown
            </Text>

            {attendanceData.map((day, index) => {
              const attendanceRate = ((day.present / day.total) * 100).toFixed(1);
              return (
                <View
                  key={day.date}
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    paddingVertical: 16,
                    paddingHorizontal: 16,
                    marginBottom: 8,
                    borderRadius: 12,
                    backgroundColor: '#f8fafc',
                    borderWidth: 1,
                    borderColor: '#e5e7eb',
                  }}
                >
                  <View style={{ flex: 1 }}>
                    <Text style={{
                      fontSize: 16,
                      fontWeight: '600',
                      color: '#1f2937',
                      marginBottom: 4,
                    }}>
                      {new Date(day.date).toLocaleDateString('en-US', {
                        weekday: 'long',
                        month: 'short',
                        day: 'numeric',
                      })}
                    </Text>
                    <Text style={{
                      fontSize: 14,
                      color: '#6b7280',
                      fontWeight: '500',
                    }}>
                      {day.present} of {day.total} students present
                    </Text>
                  </View>

                  <View style={{ alignItems: 'flex-end' }}>
                    <Text style={{
                      fontSize: 20,
                      fontWeight: '700',
                      color: parseFloat(attendanceRate) >= 80 ? '#10b981' : 
                             parseFloat(attendanceRate) >= 60 ? '#f59e0b' : '#ef4444',
                      marginBottom: 2,
                    }}>
                      {attendanceRate}%
                    </Text>
                    <View style={{
                      width: 60,
                      height: 6,
                      backgroundColor: '#e5e7eb',
                      borderRadius: 3,
                      overflow: 'hidden',
                    }}>
                      <View style={{
                        width: `${attendanceRate}%` as any,
                        height: '100%',
                        backgroundColor: parseFloat(attendanceRate) >= 80 ? '#10b981' : 
                                       parseFloat(attendanceRate) >= 60 ? '#f59e0b' : '#ef4444',
                      }} />
                    </View>
                  </View>
                </View>
              );
            })}
          </View>

          {/* Export Options */}
          <View style={{
            backgroundColor: '#ffffff',
            borderRadius: 20,
            padding: 24,
            marginBottom: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.08,
            shadowRadius: 16,
            elevation: 6,
            borderWidth: 1,
            borderColor: '#f1f5f9',
          }}>
            <View style={{
              marginBottom: 20,
            }}>
              <Text style={{
                fontSize: 20,
                fontWeight: '700',
                color: '#1f2937',
                marginBottom: 6,
              }}>
                Generate & Export Reports
              </Text>
              <Text style={{
                fontSize: 14,
                color: '#6b7280',
                fontWeight: '500',
              }}>
                Create professional attendance reports in multiple formats
              </Text>
            </View>

            <View style={{
              flexDirection: isTablet ? 'row' : 'column',
              gap: 14,
              marginBottom: 18,
            }}>
              <TouchableOpacity
                onPress={() => generateReport('excel')}
                disabled={isGenerating}
                style={{
                  flex: 1,
                  backgroundColor: isGenerating ? '#9ca3af' : '#1e40af',
                  paddingVertical: 16,
                  paddingHorizontal: 20,
                  borderRadius: 12,
                  alignItems: 'center',
                  justifyContent: 'center',
                  shadowColor: '#1e40af',
                  shadowOffset: { width: 0, height: 4 },
                  shadowOpacity: 0.2,
                  shadowRadius: 8,
                  elevation: 4,
                  borderWidth: 1,
                  borderColor: 'rgba(255,255,255,0.2)',
                }}
              >
                <Text style={{
                  color: '#ffffff',
                  fontWeight: '700',
                  fontSize: 16,
                  letterSpacing: 0.5,
                }}>
                  {isGenerating ? 'Generating...' : 'Excel Report'}
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => generateReport('pdf')}
                disabled={isGenerating}
                style={{
                  flex: 1,
                  backgroundColor: isGenerating ? '#9ca3af' : '#1e40af',
                  paddingVertical: 16,
                  paddingHorizontal: 20,
                  borderRadius: 12,
                  alignItems: 'center',
                  justifyContent: 'center',
                  shadowColor: '#1e40af',
                  shadowOffset: { width: 0, height: 4 },
                  shadowOpacity: 0.2,
                  shadowRadius: 8,
                  elevation: 4,
                  borderWidth: 1,
                  borderColor: 'rgba(255,255,255,0.2)',
                }}
              >
                <Text style={{
                  color: '#ffffff',
                  fontWeight: '700',
                  fontSize: 16,
                  letterSpacing: 0.5,
                }}>
                  {isGenerating ? 'Generating...' : 'PDF Report'}
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={emailReport}
                style={{
                  flex: 1,
                  backgroundColor: '#1e40af',
                  paddingVertical: 16,
                  paddingHorizontal: 20,
                  borderRadius: 12,
                  alignItems: 'center',
                  justifyContent: 'center',
                  shadowColor: '#1e40af',
                  shadowOffset: { width: 0, height: 4 },
                  shadowOpacity: 0.2,
                  shadowRadius: 8,
                  elevation: 4,
                  borderWidth: 1,
                  borderColor: 'rgba(255,255,255,0.2)',
                }}
              >
                <Text style={{
                  color: '#ffffff',
                  fontWeight: '700',
                  fontSize: 16,
                  letterSpacing: 0.5,
                }}>
                  Email Report
                </Text>
              </TouchableOpacity>
            </View>

            <TouchableOpacity
              onPress={scheduleReport}
              style={{
                backgroundColor: '#1e40af',
                paddingVertical: 16,
                paddingHorizontal: 20,
                borderRadius: 12,
                alignItems: 'center',
                justifyContent: 'center',
                shadowColor: '#1e40af',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.2,
                shadowRadius: 8,
                elevation: 4,
                borderWidth: 1,
                borderColor: 'rgba(255,255,255,0.2)',
              }}
            >
              <Text style={{
                color: '#ffffff',
                fontWeight: '700',
                fontSize: 16,
                letterSpacing: 0.5,
              }}>
                Schedule Automatic Reports
              </Text>
            </TouchableOpacity>
          </View>

          {/* Report History */}
          {reportHistory.length > 0 && (
            <View style={{
              backgroundColor: '#ffffff',
              borderRadius: 16,
              padding: 20,
              marginBottom: 40,
              shadowColor: '#000',
              shadowOffset: { width: 0, height: 2 },
              shadowOpacity: 0.05,
              shadowRadius: 8,
              elevation: 3,
            }}>
              <Text style={{
                fontSize: 18,
                fontWeight: '600',
                color: '#1f2937',
                marginBottom: 16,
              }}>
                Recent Reports
              </Text>

              {reportHistory.slice(0, 5).map((report) => (
                <TouchableOpacity
                  key={report.id}
                  onPress={() => shareReport(report)}
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    paddingVertical: 12,
                    paddingHorizontal: 16,
                    marginBottom: 8,
                    borderRadius: 8,
                    backgroundColor: '#f8fafc',
                    borderWidth: 1,
                    borderColor: '#e5e7eb',
                  }}
                >
                  <View style={{ flexDirection: 'row', alignItems: 'center', marginRight: 12 }}>
                    {report.format === 'excel' ? renderIcon('bar-chart' as any, 18, '#3b82f6') : report.format === 'pdf' ? renderIcon('document' as any, 18, '#ef4444') : renderIcon('email' as any, 18, '#10b981')}
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={{
                      fontSize: 16,
                      fontWeight: '600',
                      color: '#1f2937',
                      marginBottom: 2,
                    }}>
                      {report.class} - {report.period}
                    </Text>
                    <Text style={{
                      fontSize: 14,
                      color: '#6b7280',
                    }}>
                      {new Date(report.createdAt).toLocaleDateString()} • {report.averageAttendance}% avg
                    </Text>
                  </View>
                  <Text style={{
                    fontSize: 16,
                    color: '#6b7280',
                  }}>
                    →
                  </Text>
                </TouchableOpacity>
              ))}
            </View>
          )}
        </View>
      </ScrollView>
    </View>
  );
}